language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - "$HOME/.gradle"

install: true
script: "./gradlew clean build jacoco"
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi'
env:
  global:
  - CI_NAME=travis-ci
